export const ADDPARAMETER="AddNewParameter"
export const DELETEPARAMETER="DeleteTheParameter"
export const ALTERPARAMETER="AlterTheParameter"
export const SETCURRENTPARAMETER="SetTheCurrentParameter"
export const ADDOPTIONs="AddOptions"
export const SETSELECTEDPARAMETER="SetSelectedParameter"
export const RESETPARAMLIST="ResetParamList"
export const ADDTOPARAMETERLIST="AddToParamList"
export const DELETEFROMPARAMETERLIST="DeleteFromParamList"
export const TOGGLESECTION="TOGGLESECTION"
export const SETFUNCTIONDETAILS="SetFunctionDetails"
export const ALTERFUNCTIONDETAILS="AlterFunctionDetails"
export const RESETCURRENTPARAMETER="ResetCurrentParameter"
export const ADDTOOPTIONSLIST = "AddToOptionsList"
export const REMOVEFROMOPTIONSLIST = "RemoveFromOptionsList"
export const ALTEROPTIONSLIST = "AlterOptionsList"
export const RESETALLDATA="ResetAllData"

